### ISSUE TITLE
Parse the ec2 instance IP from Terraform and reuse it within Ansible configuration within Jenkinsfile

### ISSUE THREAD

**Issue by Hawaiideveloper** [Hawaiideveloper/Infastructure-as-Code-Sample_Env#6]
Desired result would be that I run a Jenkins Pipeline Job that would:

## Phase 1 (Build)
- [ ] Launch the terraform environment
    - [ ] Print the ec2 instance and write it to a host file for Ansible
- [ ] Run Ansible against the host file Terraform populated
    - [ ] Install Docker 
        - [ ] pull container Node JS
        - [ ] pull container MongoDB
        - [ ] pull container Jenkins

## Phase 2 (Test)
- [ ] Run Docker compose to run the required applications in tandem
- [ ] Curl the replies and look for 302s 
            {
        if successful then proceed to phase 3
        else if print "known error"
            }

## Phase 3 (Deploy)
- [ ] Stop all running containers
- [ ] Run Kubernetes dashboard
- [ ] Start all microservices
- [ ] curl for replies in the Microservices and provide all greens in the pipeline

[So far I read this](https://www.terraform.io/docs/commands/output.html) this which leads me to believe that 

## The "Use" in automation will:
---

- [ ] Parse the output using a JSON command-line parser such as jq:
```
$ terraform output -json instance_ips | jq -r '.[0]'
54.43.114.12
```

For the common case of directly using a string value in a shell script, you can use -raw instead, which will print the string directly with no extra escaping or whitespace.

```
$ terraform output -raw lb_address
my-app-alb-1657023003.us-east-1.elb.amazonaws.com
```

The -raw option works only with values that Terraform can automatically convert to strings. Use -json instead, possibly combined with jq, to work with complex-typed values such as objects.

**Comment by Hawaiideveloper** [comment]
### Plan A:
---
### [Link from Ansible describing a possible solution](https://docs.ansible.com/ansible/latest/collections/community/general/terraform_module.html)
*It looks like I had it reversed and it is **Ansible** that can pull information from Terraform.*

**Comment by Hawaiideveloper** [comment]
### Plan B:
---
Link to [Digital Ocean excerpt](https://victorops.com/blog/writing-ansible-playbooks-for-new-terraform-servers) and it mentions:

*prepend a [remote-exec](https://www.terraform.io/docs/provisioners/remote-exec.html) provision step before we run the **[local-exec](https://www.terraform.io/docs/provisioners/local-exec.html)** in the pipeline containing a simple echo command:*

###### [local-exec](https://www.terraform.io/docs/provisioners/local-exec.html)
```
provisioner "local-exec" {
  command = "sleep 120; ansible-playbook -i '${digitalocean_droplet.www-example.ipv4_address}' playbook.yml"
}
```

###### [remote-exec](https://www.terraform.io/docs/provisioners/remote-exec.html)
```
provisioner "remote-exec" {
    inline = ["echo 'Hello World'"]

    connection {
        type        = "ssh"
        user        = "root"
        host        = "${self.ipv4_address}"
        private_key = "${file(var.ssh_key_private)}"
    }
}
```

**Comment by Hawaiideveloper** [comment]
### Suggestion would be to append the [main.tf](https://github.com/Hawaiideveloper/Infastructure-as-Code-Sample_Env/blob/main/TerraForm/production_site/main.tf) file with similar syntax from plan B mentioned above

*Then call the output variable of the ip_address and see if we can launch our docker install and pull Jenkins down shortly afterwards.*
- with *remote commands* within the main.tf file
- with *local commands* within the main.tf file

#### The pipeline need to be segregated into 5 steps for both granular views and scale processes:

- [ ] Step 1: Base image that configures an EC2 to become a Docker Host: uses plan B from above
- [ ] Step 2: Base image does step 1 and pulls Jenkins: uses ansible playbook
- [ ] Step 3: Base image does step 2 and creates one Jenkins slave container 
- [ ] Step 4: Base images does step 1 and installs Kubernetes that uses plan B from above
- [ ] Step 5: Base images does step 4 and runs all containers under Kubernetes using Ansible shell command from within Terraform

*After sorting through my thoughts it appears plan B might be exactly what I am looking for.*

**Comment by Hawaiideveloper** [comment]
To get the iP of the ```unknown IP``` from Terrafform ... it shows the example from  [plan_B](https://github.com/Hawaiideveloper/Infastructure-as-Code-Sample_Env/issues/6#issuecomment-751418702)

you need to review this and fast forward to 4:36 

https://youtu.be/QxgJlJgGA0E

**Comment by Hawaiideveloper** [comment]
I will test that and if it works we are ready for our pipeline

**Comment by Hawaiideveloper** [comment]
example looks similar to:


resource "aws_instance" "webserver" {
  ami                    = data.aws_ami.ubuntu.id
  availability_zone      = "us-west-2a"
  instance_type          = var.dev_instance_type
  key_name               = aws_key_pair.you-have-a-pem-already.key_name
  vpc_security_group_ids = [aws_security_group.allow-all.id]
  subnet_id              = aws_subnet.production.id

  tags = {
    Name = "Clexys-Docker-Host"
  }

### the magic starts here to configure the instance


provisioner "remote-exec" {
  inline = ["echo 'ssh is now connected'"]



connection {
  type = "ssh"
  user = "${var.ssh_user}"
  private_key = "${file("${var.private_key_path}")}"
    }
}

  provisioner "local-exec" {
  command = "ansible-playbook -i ${aws_eip.webserver.public_ip}, --private-key ${var.private_key_path} "
  }




# we tell terraform to give us the elastic IP address of our instance
output "public_ip" {
  value = aws_eip.webserver.public_ip
}

**Comment by Hawaiideveloper** [comment]
Now closing as solved
